id: P68C596F3
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG10008
  instance_id: http://purl.bdrc.io/resource/IE1KG4783
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྟགས་རིགས་ཀྱི་རྣམ་གཞག་རྒྱས་པ་རིགས་ལམ་བློ་གྲོས་མིག་འབྱེད།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1629
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    d6ac1dcf74914afd98d8a8e1e5093ca8:
      title: པོད ༡་རྟགས་རིགས་ཀྱི་རྣམ་གཞག་རྒྱས་པ་རིགས་ལམ་བློ་གྲོས་མིག་འབྱེད
      volume_number: 1
      base_file: UT1KG4783_I1KG4845_0000.txt
      reference: http://purl.bdrc.io/resource/VL79D8B8B508B20C25
      image_group: I1KG4845
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4783
  - http://purl.bdrc.io/resource/W1KG4783
  ocr_software: Namsel
created_at: '2021-12-22T10:43:28.579603'
last_modified_at: '2021-12-22T10:43:28.579608'
